version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_scap
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdscap_sd_v3
      MYSQL_USER: user_scap
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3309:3306'
